### ISSUE TITLE
Include Article Source as Well

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [chshersh/pragmatic-category-theory#1]
I've been thinking about some features to your articles. Could you add the article source here as well?

**Comment by chshersh** [comment]
HI @BebeSparkelSparkel,

The links to articles are already mentioned in README:

![image](https://github.com/user-attachments/assets/fd907ae3-74ca-4eb5-a931-5142fadb8f2a)

Is what you mean by saying the original source? Or something else?

**Comment by BebeSparkelSparkel** [comment]
Sorry for being unclear. I think you used markdown or something similar when writing your articles. If you are open to the idea, I would like to be able provide some potential edits to these and submit them as pull requests.

**Comment by chshersh** [comment]
Ah, I see, it makes sense.

Ideally, I want to rewrite my entire personal blog and host the sources of all articles there but it may take a few years 😅 

It should be possible to develop a short-term solution and host the source of articles here. I'll work on it.

**Comment by chshersh** [comment]
Hi @BebeSparkelSparkel,

Apologies, it took me a while to get this done. I was on vacation and then got sick and then decided to rewrite my entire personal website to Elm to host all my articles there.

The source of articles is now stored in my personal repository:

* https://github.com/chshersh/chshersh.github.io/tree/develop/posts

So feel free to submit the edits there if you're still interested!

The articles are not yet hosted on my website. They'll be hosted once I complete the following issue:

* https://github.com/chshersh/chshersh.github.io/issues/82

But you can submit edits already, and they'll be included in the version once I finally publish my blog!

**Comment by BebeSparkelSparkel** [comment]
Thanks, I'll try to remember the edits I wanted.

**Comment by BebeSparkelSparkel** [comment]
What do you use for rendering the md?

**Comment by chshersh** [comment]
@BebeSparkelSparkel I use `pandoc`.

This is my HTML template:

- https://github.com/chshersh/chshersh.github.io/blob/develop/template-article.html

And this is [the Bash script](https://github.com/chshersh/chshersh.github.io/blob/develop/rerender.sh) to rerender all articles:

```bash
#!/bin/bash

set -euo

for file in posts/*; do
    file_name=$(basename "$file")
    article_name="${file_name%.*}"

    # Convert Markdown to HTML
    pandoc "$file" \
      --template=template-article.html \
      --output "blog/${article_name}.html"

    echo "$file -> blog/${article_name}.html"
done
```
